apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    pv: redis-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: db-group
          operator: In
          values:
          - group-2
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"
  claimRef:
    namespace: default
    name: redis-data-redis-0