apiVersion: v1
kind: PersistentVolume
metadata:
  name: room-pv
  labels:
    pv: room-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/room-db"
  claimRef:
    namespace: default
    name: room-db-data-room-db-0