apiVersion: v1
kind: ConfigMap
metadata:
  name: game-configmap
data:
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  REFRESH_TOKEN_EXPIRE_DAYS: {{ .Values.config.refreshTokenExpireDays | quote }}
