{{- if .Values.db.hostPath.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-pv
  labels:
    pv: game-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: db-group
          operator: In
          values:
          - {{ .Values.db.nodeGroup }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.db.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.db.hostPath.path }}"
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: game-db-data-game-db-0
  {{- end }}