apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game-db
spec:
  serviceName: game-db-service
  replicas: 1
  selector:
    matchLabels:
      app: game-db
  template:
    metadata:
      labels:
        app: game-db
    spec:
      containers:
      - name: mysql
        image: {{ .Values.db.image }}
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: game-db-secret
        volumeMounts:
        - name: game-db-data
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.db.resources | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: game-db-data
    spec:
      storageClassName: ""
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.db.storage }}
