ingress:
  host: "dev.chess.internal"

resourcequota:
  hard:
    requests.cpu: "1300m"
    requests.memory: "2900Mi"
    limits.cpu: "2700m"
    limits.memory: "4200Mi"

frontend:
  enabled: true

secret:
  enabled: false
  externalSecret:
    remoteRef:
      key: "chess/dev/ghcr"

auth:
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/dev/auth"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "chess/dev/auth-db"

room:
  replicaCount: 1
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/dev/room"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "chess/dev/room-db"

game:
  replicaCount: 1
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/dev/game"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "chess/dev/game-db"

redis:
  storageClassName: gp3
  hostPath:
    enabled: false
