ingress:
  host: "staging.chess.internal"

resourcequota:
  hard:
    requests.cpu: "3150m"
    requests.memory: "5128Mi"
    limits.cpu: "6650m"
    limits.memory: "8456Mi"

frontend:
  enabled: true

secret:
  enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/ghcr"

auth:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/auth"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/auth-db"

room:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/room"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/room-db"

game:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/game"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/game-db"

redis:
  storageClassName: gp3
  hostPath:
    enabled: false
