ingress:
  host: "chess.yourdomain.com"
  nginx:
    enabled: false
  alb:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip

resourcequota:
  hard:
    requests.cpu: "2300m"
    requests.memory: "2700Mi"
    limits.cpu: "4900m"
    limits.memory: "5300Mi"

frontend:
  enabled: false

secret:
  enabled: false
  externalSecret:
    remoteRef:
      key: "chess/prod/ghcr"

auth:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/prod/auth"
  db:
    enabled: false
    hostPath:
      enabled: false
    cidr: "10.0.0.0/16"

room:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/prod/room"
  redisCidr: "10.0.0.0/16"
  db:
    enabled: false
    hostPath:
      enabled: false
    cidr: "10.0.0.0/16"

game:
  hpa:
    enabled: true
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "chess/prod/game"
  redisCidr: "10.0.0.0/16"
  db:
    enabled: false
    hostPath:
      enabled: false
    cidr: "10.0.0.0/16"

redis:
  enabled: false
  hostPath:
    enabled: false
