ingress:
  host: "dev.chess.internal"

resourcequota:
  hard:
    requests.cpu: "1350m"
    requests.memory: "3028Mi"
    limits.cpu: "2850m"
    limits.memory: "4456Mi"

frontend:
  enabled: true

secret:
  enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/ghcr"

auth:
  replicaCount: 1
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/auth"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/auth-db"

room:
  replicaCount: 1
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/room"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/room-db"

game:
  replicaCount: 1
  secret:
    enabled: false
  externalSecret:
    remoteRef:
      key: "/chess-shared/game"
  db:
    storageClassName: gp3
    hostPath:
      enabled: false
    secret:
      enabled: false
    externalSecret:
      remoteRef:
        key: "/chess-shared/game-db"

redis:
  storageClassName: gp3
  hostPath:
    enabled: false
