apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-deployment
  labels:
    app: chess-room-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chess-room-service
  template:
    metadata:
      labels:
        app: chess-room-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
      - name: init-room-db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - secretRef:
            name: room-secret
        resources:
          {{- toYaml .Values.initContainer.resources | nindent 10 }}
      containers:
      - name: chess-room-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: room-secret
        - configMapRef:
            name: room-configmap
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
