{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: room-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.secret.rootPassword | quote }}
  MYSQL_USER: {{ .Values.db.secret.user | quote }}
  MYSQL_PASSWORD: {{ .Values.db.secret.password | quote }}
  MYSQL_DATABASE: {{ .Values.db.secret.database | quote }}
{{- end }}