{{- if .Values.db.enabled }}
{{- if .Values.db.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: room-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.secret.rootPassword | quote }}
  MYSQL_USER: {{ .Values.db.secret.user | quote }}
  MYSQL_PASSWORD: {{ .Values.db.secret.password | quote }}
  MYSQL_DATABASE: {{ .Values.db.secret.database | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: room-db-secret
spec:
  refreshInterval: {{ .Values.db.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.db.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.db.externalSecret.secretStoreRef.kind }}
  target:
    name: room-db-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.db.externalSecret.remoteRef.key | quote }}
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.db.externalSecret.remoteRef.key | quote }}
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.db.externalSecret.remoteRef.key | quote }}
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.db.externalSecret.remoteRef.key | quote }}
        property: MYSQL_DATABASE
{{- end }}
{{- end }}
