{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret
spec:
  refreshInterval: {{ .Values.secret.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secret.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secret.externalSecret.secretStoreRef.kind }}
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.secret.externalSecret.remoteRef.key | quote }}
        property: .dockerconfigjson
{{- end }}
