apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: chess-frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-frontend-service
  template:
    metadata:
      labels:
        app: chess-frontend-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: chess-frontend-service
        image: ghcr.io/shyrimon2000-tech/chess-frontend-service:1.0.0
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"