include "root" {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "../../../modules/argocd"
}

dependency "eks" {
  config_path = "../eks"

  mock_outputs = {
    cluster_name                       = "mock-cluster"
    cluster_endpoint                   = "https://mock.eks.amazonaws.com"
    cluster_certificate_authority_data = "bW9jaw=="
  }
  mock_outputs_allowed_terraform_commands = ["plan", "validate", "init", "destroy"]
}

# Ordering-only dependency — argocd's own Ingress resource is validated by
# ingress-nginx's admission webhook. Without this, both units can apply in
# parallel and argocd's helm_release fails with "no endpoints available for
# service ingress-nginx-controller-admission" if it races ahead. Its output
# isn't consumed here; the block itself is what enforces the apply order.
dependency "ingress_nginx" {
  config_path = "../ingress-nginx"

  mock_outputs = {
    load_balancer_hostname = "mock-nlb-1234567890.elb.us-east-1.amazonaws.com"
  }
  mock_outputs_allowed_terraform_commands = ["plan", "validate", "init", "destroy"]
}

generate "helm_provider" {
  path      = "helm_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "helm" {
  kubernetes = {
    host                   = "${dependency.eks.outputs.cluster_endpoint}"
    cluster_ca_certificate = base64decode("${dependency.eks.outputs.cluster_certificate_authority_data}")
    exec = {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", "${dependency.eks.outputs.cluster_name}"]
    }
  }
}
EOF
}

generate "kubectl_provider" {
  path      = "kubectl_provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "kubectl" {
  host                   = "${dependency.eks.outputs.cluster_endpoint}"
  cluster_ca_certificate = base64decode("${dependency.eks.outputs.cluster_certificate_authority_data}")
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", "${dependency.eks.outputs.cluster_name}"]
  }
}
EOF
}

inputs = {
  name = "chess-shared"

  # Root Application watches helm/git-ops/shared/ — the actual per-env
  # ApplicationSet buckets (dev automated, staging manual) are hand-written
  # YAML there now, not generated by Terraform. See that folder for the
  # per-env details this used to hold.
  gitops_dir              = "shared"
  gitops_target_revision  = "dev"

  # Split per namespace, not one combined project: dev's bucket auto-syncs
  # with no human review, so its AppProject must not list staging as an
  # allowed destination — see app_projects description in variables.tf.
  app_projects = {
    "apps-dev"     = ["dev"]
    "apps-staging" = ["staging"]
  }

  ingress_enabled = true
}
