apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <your-root-password>
  MYSQL_USER: chess_user
  MYSQL_PASSWORD: <your-password>
  MYSQL_DATABASE: chess_auth_db
