apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://chess_user:<your-password>@auth-db-0.auth-db-service.default.svc.cluster.local:3306/auth_db
  JWT_SECRET_KEY: <your-jwt-secret>
