apiVersion: v1
kind: Secret
metadata:
  name: game-secret
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://chess_user:<your-password>@game-db-0.game-db-service.default.svc.cluster.local:3306/game_db
  REDIS_URL: redis://redis-0.redis-service.default.svc.cluster.local:6379
  JWT_SECRET_KEY: <your-jwt-secret>
