apiVersion: v1
kind: Secret
metadata:
  name: room-secret
type: Opaque
stringData:
  DATABASE_URL: mysql+pymysql://chess_user:<your-password>@room-db-0.room-db-service.default.svc.cluster.local:3306/room_db
  REDIS_URL: redis://redis-0.redis-service.default.svc.cluster.local:6379
  JWT_SECRET_KEY: <your-jwt-secret>
